### ISSUE TITLE
Run build in case packages changes?!

### ISSUE THREAD

**Issue by andrasbacsai** [webstudio-is/webstudio#179]
We need to manually run `yarn build` when we change something in packages and would like to run for example `yarn checks`.

**Comment by andrasbacsai** [comment]
I definitely need more information on this form @kof, so please extend it as much as you could.

**Comment by kof** [comment]
some things that we do in build are slow by design, e.g. in react-sdk we have ` "build": "yarn build:mdn-data && yarn build:args && yarn build:lib",` and so we can't just naively run yarn build from the root because it will call things like that.

But if turborepo can have a cache that makes sure do not cause any work for things that didn't change, we would be able to run yarn build on postinstall I guess?

Another option is to never put anything into the "build" script if it shouldn't run on every postinstall. In case of react-sdk we would need to remove `build:mdn-data` and `build:args ` from  build.
