### ISSUE TITLE
Transitions section

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio#1939]
Design is in draft stage, many thingsa are not finished there

https://www.figma.com/file/EfzZ2w94KpmUviZJSBgxCd/%F0%9F%92%AD-Webstudio-Design-Work?type=design&node-id=6424-30607&mode=design&t=LXNO2FwknePYv6qR-0

- [ ] Reuse the functional logic between background layers and transitions
- [ ] Render the same sortable list as with backgrounds, same accessibility
- [ ] Render floating panel
- [ ] Instead of "Type", it should be "Property". The control is combobox, it should support all properties, not just randomly selected once. User can type it, can autocomplete it, can select "All"
- [ ] Duration is CssValueInput with a fixed units list, default is 200ms
- [ ] Easing is a combobox with all possible easing options from https://easings.net/ as well as ability to type a custom one
- [ ] Delay is the same as duration, default is 0

**Comment by JayaKrishnaNamburu** [comment]
I looked into this, i have several questions on this.

- In the first iteration, is there any plans to allow users itself to add transitions as they can with `box-shadow` and `background`. Because i see that in figma description but missing from the design.
![Screenshot 2023-10-09 at 17 14 33](https://github.com/webstudio-is/webstudio/assets/11075561/7e1063f0-ed88-4fde-91e6-baf3cfb260a9)

- Do we have a list of all the css attributes that are needed to show in the list. Or the list contains the time-definition-property from the actual spec. 
![Screenshot 2023-10-09 at 17 15 32](https://github.com/webstudio-is/webstudio/assets/11075561/35b55e49-9e0c-4672-8acc-2c7c6ce78e42)

- If users are allowed to use custom transition properties. Then the icons here are difficult to represent those. Eg, there should be icons for `linear`, `steps`, `cubic-beizer` etc. Or else there should be independent icons for these, `ease` `ease-in`, `ease-out`, `linear`, `ease-in-out`. Because the rest of them needs user inputs eg: `step(x, y)`, `cubic-beizer(..)`
![Screenshot 2023-10-09 at 17 16 54](https://github.com/webstudio-is/webstudio/assets/11075561/6005b3e9-94f5-4f2b-8a6d-a59b59719da5)

The best way seems to be, to show the full layer as text as it shown for box-shadow. It's additional meta for users to remember and relate the icons with the respective transition(But that's personal opinion). 

- The heading section here, needs a `+` icon. So when clicked adds a default layer of transition and then users can edit it. On click of the layer it can open this floating window with all the values popped-up. 
![Screenshot 2023-10-09 at 17 19 00](https://github.com/webstudio-is/webstudio/assets/11075561/fe707efc-fbf2-4cec-b32a-aa0f8d7c0eb2)
I made some of these changes from like the `+` icon etc. While starting this, but i would suggest to look into this design wise and bring it closer to the UX of other properties :)

**Comment by kof** [comment]
>  any plans to allow users itself to add transitions

Yes, it's similar to how it works in wf

> Do we have a list of all the css attributes that are needed to show in the list

Seems like design is wrong, because we should be using a combobox that allows selecting from an existing list similar to webflow, but also allows to type any valid CSS property name

> If users are allowed to use custom transition properties. Then the icons here are difficult to represent those.

Skip the icon. It was just an idea to use it to represent the curve right away, but I don't see how this would work in such a tiny space.

>  bring it closer to the UX of other properties

I think they should all behave the same way: background, shadows, transitions, all of the multi-part values. Right now they add an item but don't open it, user has to click again. I don't think its been a problem so far

**Comment by taylornowotny** [comment]
I will finish designing this feature soon 👍

**Comment by JayaKrishnaNamburu** [comment]
![Screenshot 2023-10-20 at 13 13 55](https://github.com/webstudio-is/webstudio/assets/11075561/32368d3b-3cbe-49b7-8151-5cf1161fcdfe)

I was experimenting with the values, and then suddenly i remembered, the UX for defining the triggers is also missing 😅.  Users can define the transitons. But at the same time, how to they define the triggers that activate them like, `hover` etc. You can play around with the preview link here
https://github.com/webstudio-is/webstudio/pull/2511

**Comment by kof** [comment]
All states are handled on style sources, its already working  for you if you add the properties on the right token

**Comment by JayaKrishnaNamburu** [comment]
Ah that's nice, didn't knew states are already supported 😅  👍

**Comment by JayaKrishnaNamburu** [comment]
Just tested it, works as expected 😄. Now, it brings the old question. Should the transitions be added in canvas mode. I vote to show them only in preview more.
![Screen Recording 2023-10-20 at 13 29 00](https://github.com/webstudio-is/webstudio/assets/11075561/4247ab2d-f592-4a98-8dae-579ae66b6ba4)

**Comment by kof** [comment]
I think we should do what wf does there:

1. transition can be added on base token, not on a state (they have an error showing when you are trying to add transition when in state selected)

<img width="251" alt="Screenshot 2023-10-20 at 11 20 43" src="https://github.com/webstudio-is/webstudio/assets/52824/fc80743d-fd26-4eee-9aea-213bdfba6750">


2. They do allow transitions on canvas in build mode

Please try it there on wf.

**Comment by JayaKrishnaNamburu** [comment]
Yes, was mainly referring to the canvas itself. Will refer to them and see how they are handling it 👍

**Comment by kof** [comment]
You never want transition to be set on :hover and co, because CSS needs to ideally know upfront what the transition is to avoid unexpected effects.

**Comment by taylornowotny** [comment]
2nd what Oleg is saying.

As a long time Webflow user I like that the canvas is as close as
reasonable to the published site so I can see what the user is seeing. If I
have to turn on preview to test transitions that slows me down.

**Comment by kof** [comment]
@JayaKrishnaNamburu we were just discussing which properties go into properties list, I checked mdn-data package we are using does have this information,  https://github.com/mdn/data/blob/main/css/properties.json#L1790 you will need to touch css-data and include it there as well, then in the combobox filter out nonAnimatable properties

**Comment by taylornowotny** [comment]
Design is complete @JayaKrishnaNamburu 

Please ask myself or @kof if you have questions. It is very similar to the box-shadows design.

<img width="582" alt="Screenshot 2023-10-24 at 3 26 18 PM" src="https://github.com/webstudio-is/webstudio/assets/86495896/0c4f795f-b025-49c9-bb0e-748d53a0f1cd">

https://www.figma.com/file/xCBegXEWxROLqA1Y31z2Xo/%F0%9F%93%96-Webstudio-Design-Docs?type=design&node-id=8085-44296&mode=design

**Comment by JayaKrishnaNamburu** [comment]
Closing this too, as the section is handled now. If there are any further improvements / new requirements. Let's have a new one for it.
