### ISSUE TITLE
EDU - How to use Design Tokens

### ISSUE THREAD

**Issue by itsNintu** [webstudio-is/webstudio#2240]
## Outline:

**Introduction**
- Importance of CSS in modern web layouts
- The role of Webstudio Design Tokens in CSS

**Creating and Applying Tokens**
- How to create a token
- - How to know which token is currently selected/active
- - How to know which styles are active on the current token
- - How to apply styles to specific breakpoints
- - How to apply styles to specific states
- Applying the created token to different elements

**Editing Tokens**
- Applying the same token on multiple elements
- Editing styles on any element with the main token applied
- Renaming a token

**Removing Tokens**
- Removing tokens from elements
- Deleting tokens completely

**Duplicating Tokens**
- The concept of duplicating tokens using local as an example

**Combining Tokens: An Alternative to Duplicating**
- Definition and creation of utility tokens
- How combining utility tokens works with base tokens
- Ordering of tokens and specificity

**Global Tokens: Applying Specific Styles Broadly**
- Definition and creation of global tokens
- Applying global styles to different kinds of elements

**Conclusion & Recap: Balancing Local, Global, and Utility Tokens**
- Differences between duplicating a token and using a utility or global token
- The practicality of using each type in different scenarios

**Comment by kof** [comment]
1. We just made local style source fixed position at the end https://github.com/webstudio-is/webstudio/pull/2229

I would either record it on that branch from preview or just assume in the demo Local will always be at the end and you can't drag tokens behind the local

**Comment by taylornowotny** [comment]
"Tokens are how you re-use styles in your project. They work a lot like CSS classes, only better"
I would say this, verbatim, in the intro. It's important to explain "why" to use tokens before explaining "how".

So I'm not sure why the "Global Tokens" section is at the end of this outline. I would make this the first section.

Please do not divide tokens into categories of global, local, base, and utility. Tokens are all global except for the one Local token which is on every instance and can't be removed, renamed, or re-used. Utility tokens are not a kind of token, just an optional methodology for using them. Since every token the user makes will be global, it's not necessary to call it global. **So please do not say "utility tokens" or "global tokens" or "base tokens" becuase these are not different. It's all just "tokens".**

**Comment by kof** [comment]
Yeah, separate the concepts for naming tokens from actually webstudio specific stuff, because naming is not something we enforce. Do mention tailwind-style utility tokens and semantic tokens as 2 different naming paradigms.

**Comment by TrySound** [comment]
Why "local" is token? The title above input says "Style sources". So we ended with "Local style source" and "Token style source". Why change it now?

**Comment by HananoshikaYomaru** [comment]
how do you use tailwind in webstudio? the doc is not included.

**Comment by kof** [comment]
tailwind is a compiler that we don't use in webstudio, you can use tailwind-style token simply by doing it that way, but I don't recommend this approach as its simply not needed in the visual environment
