### ISSUE TITLE
Command and search UI

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio#2354]
The cmd+k UI for search, shortcuts, commands and many other things

https://www.figma.com/file/EfzZ2w94KpmUviZJSBgxCd/%F0%9F%92%AD-Webstudio-Design-Work?type=design&node-id=9829%3A38419&mode=design&t=t5sSwmzkm4OOtQyM-1

See also https://github.com/webstudio-is/webstudio/issues/1696

**Comment by markxtang** [comment]
Updated the [cmd+K menu](https://www.figma.com/file/EfzZ2w94KpmUviZJSBgxCd/%F0%9F%92%AD-Webstudio-Design-Work?type=design&node-id=9744%3A36623&mode=design&t=0cFRd2W8IfVMR1ox-1) based on the Discord Conversation. For the cmd-k shortcut, I figured it should be visible within the main logo menu. 

Here's a video walkthrough of the prototype (sound on)

https://github.com/webstudio-is/webstudio/assets/122043657/6b28780d-e027-4f9c-8ee6-fc1b6480c243

**Comment by kof** [comment]
^ is  for windows, ⌘ - mac

**Comment by kof** [comment]
I still feel bad about the amount of lines I see on the prototype, maybe they could be less invasive, idk, happy to be wrong about them @taylornowotny

**Comment by taylornowotny** [comment]
I'll give it a final workover before it's ready for dev. It's a good design, just needs some layout adjustments.

I'll use a section title for each section which will give them more space. I'll reduce the width of the window as the content simply doesn't need this much width. And I'll remove the separator lines between each item.

**Comment by markxtang** [comment]
@taylornowotny I put back the older skinnier version of the command panel because it sounds a lot like what you're talking about. I made it wider is response to @kof 's earlier feedback 

> if this is a dialog that opens up in the middle then it should be probably landscape size, no?

https://www.figma.com/file/EfzZ2w94KpmUviZJSBgxCd/%F0%9F%92%AD-Webstudio-Design-Work?type=design&node-id=10011%3A33952&mode=design&t=g1D6fkjNLMCVDEtu-1

**Comment by taylornowotny** [comment]
Understood, thanks!

Despite the feedback, the main consideration for determining the width of the panel should be its content. There's no benefit to a wider panel here, it just ends up stretching the items which can actually make it harder to associate the shortcut with its name. I'm assuming that's why you added lines between each item. Thus the panel is easier to read and lines are not needed if it's narrower.

**Comment by kof** [comment]
wide search UI is kinda what you get on macos, in webflow ... and many others, narrow feels wrong optically and probably will need to get wider again once we have more stuff in the search box ...

**Comment by kof** [comment]
maybe the problem with shortcuts can be fixed by having them before the commands or right after them, not at the end of the line? idk

**Comment by markxtang** [comment]
I tried a 2 column layout

![image](https://github.com/webstudio-is/webstudio/assets/122043657/22f35134-6157-44aa-8dfa-dd4eb1bc24b8)

**Comment by kof** [comment]
I like the 2-column a ton, because it gives us room for many categories, not just those that fit in the horizontal space as tabs

**Comment by kof** [comment]
things we can do in the future: 
- search shorcuts
- search components
- search the instances with text or instance name across all pages
- search pages
- search commands
- search plugins
- search any generic help that could be answered by gpt (e.g. css/html help)

**Comment by taylornowotny** [comment]
Nice work @markxtang 

Agreed on the 2-column direction to afford room for all the potential categories

**Comment by taylornowotny** [comment]
Question - what's the standard way to represent holding down a key + mouse click in a shortcut?

**Comment by taylornowotny** [comment]
Requested changes @markxtang :

- [ ] Rather than searching all categories by default, we should give an "All" category. Then when a search term is entered, it searches the category that the user has currently selected without changing it on them.

- [ ] And for the "All" results category we should show the different subcategories as section titles.

- [ ] The components don't need to be separated by categories IMO. If we show categories under the "All" tab then we get three levels of nesting, which we don't have a design for (eg. All -> Components -> Radix)

**Comment by markxtang** [comment]
@taylornowotny here's an update

https://www.figma.com/file/EfzZ2w94KpmUviZJSBgxCd/%F0%9F%92%AD-Webstudio-Design-Work?type=design&node-id=9963%3A66746&mode=design&t=Uy73oK1C138szECP-1

**Comment by taylornowotny** [comment]
Great work @markxtang thank you! It looks really nice and useful.

I will finalize the layout and write the docs soon

**Comment by kof** [comment]
Closing in favor of https://github.com/webstudio-is/webstudio/issues/1696
