### ISSUE TITLE
Fix the main tooltip for Transitions

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio#2665]
The Transition tooltip is busted

To do:
- [ ] Show tooltip when the label is hovered even when no value is applied. Please update Box Shadows, Backgrounds, and Transitions
- [ ] Add tooltip description from the design
- [ ] Tooltips on properties have a fixed width of 208px

Current
<img width="266" alt="Screenshot 2023-11-30 at 10 27 42 AM" src="https://github.com/webstudio-is/webstudio/assets/86495896/57479962-44b3-4927-a93f-943a8a8697e5">

Design
<img width="342" alt="Screenshot 2023-11-30 at 11 13 14 AM" src="https://github.com/webstudio-is/webstudio/assets/86495896/e9f2d779-c3c0-4ef8-a277-2e902b4c27c4">

Figma
https://www.figma.com/file/xCBegXEWxROLqA1Y31z2Xo/%F0%9F%93%96-Webstudio-Design-Docs?type=design&node-id=8086%3A51795&mode=design&t=KA5xOTf6y2M5HKvO-1

**Comment by taylornowotny** [comment]
> regarding the removal of properties decleartion from the tooltip

I changed my mind about this so forget it. I removed the point from the issue.

FYI, the CSS declaration is the gray mono text that tells the literal CSS name for the property. Sometimes the style panel does not use exactly the same names as CSS, so we give the CSS name in the tooltip to help the user learn CSS and troubleshoot more easily.

Screenshot is from our tooltips documentation.
![Uploading Screenshot 2023-11-30 at 11.15.24 AM.png…]()
https://www.figma.com/file/xCBegXEWxROLqA1Y31z2Xo/%F0%9F%93%96-Webstudio-Design-Docs?type=design&node-id=5025%3A52256&mode=design&t=KA5xOTf6y2M5HKvO-1

**Comment by JayaKrishnaNamburu** [comment]
Ok Taylor, will add the changes. And add you as reviewer for testing it. Thanks for the details 👍

**Comment by JayaKrishnaNamburu** [comment]
@taylornowotny the tooltips requirements are still a little bit confusing for me. Let me explain my question in detail here.
Let's talk only about background section now. I have two possible states of background section header

The `intiial` state, when there is no layer to it, and there is nothing to reset here.
![Screenshot 2023-12-11 at 12 00 15](https://github.com/webstudio-is/webstudio/assets/11075561/c1db6e69-7921-4bba-bf3e-136b586f4828)

The secondary state, where users get a tooltip to reset if any values are changes in the layer. This happens if the background undergone any change.
![Screenshot 2023-12-11 at 12 00 23](https://github.com/webstudio-is/webstudio/assets/11075561/27b9d1ff-9be6-4907-b9fc-bbf70fa595cd)

Now, let's talk about the new tooltip design
![Screenshot 2023-12-11 at 12 00 04](https://github.com/webstudio-is/webstudio/assets/11075561/c2748490-3cf1-48df-a8e6-e570273f2b50)
My understanding is, this should happen only in the first state, when users did't touch the property. If the property undergone any change. The tooltip from the second screenshot comes by. Did i get it right ?

**Comment by taylornowotny** [comment]
@JayaKrishnaNamburu Yes, you are right! Please make sure the description is matched to the design too :)

**Comment by JayaKrishnaNamburu** [comment]
cool cool, will make the changes and let you know 👍

**Comment by taylornowotny** [comment]
Thanks, @JayaKrishnaNamburu You're a rock star 🌟

**Comment by JayaKrishnaNamburu** [comment]
Fixed in https://github.com/webstudio-is/webstudio/pull/2699

**Comment by kof** [comment]
🎉
