### ISSUE TITLE
chore: Add issue and Pr template

### ISSUE THREAD

**Issue by anikdhabal** [webstudio-is/webstudio#2723]
eg:-
![Screenshot 2024-01-01 224406](https://github.com/webstudio-is/webstudio/assets/81948346/6db3b9b0-989b-4a44-bd80-4ccda441e7ed)

![Screenshot 2024-01-01 224351](https://github.com/webstudio-is/webstudio/assets/81948346/ac5f0129-c4f9-42be-b3fb-4826e7075bd8)

**Comment by anikdhabal** [comment]
I want to tackle this one.

**Comment by kof** [comment]
This is something to tacked based on the experience and the needs of the core team, so that people who need to handle the issues and understand the case, can get all the information we need. So far there hasn't been enough issues from external contributors to make a template, we will get there when we see the need.

I am gonna close it for no. PR template already exists though.
