### ISSUE TITLE
Doesn't work offline?

### ISSUE THREAD

**Issue by llagerlof** [webstudio-is/webstudio#3018]
Is it mandatory to login on Google or GitHub to use the software?

Is there a way to run it offline?

**Comment by kof** [comment]
If you mean as a consumer - currently no way, its not ready for this type of use case. For development locally we have env settings:
DEV_LOGIN=true
AUTH_SECRET=yourpassword

**Comment by kof** [comment]
I am going to close this, since its a question and we do have thoughts on this, but it hasn't been highest priority. We should create an issue with an overview for what it takes to make webstudio run fully offline as a consumer app.

**Comment by kryoqa** [comment]
Can an option be provided to login manually using any email address instead of going through Google/Github. Google, I can understand as most people have one account. But the Github account seems perplexling. I assume when non-techy users try to create an account, they might turn away. And privacy centric folks/those who prefer open source alternatives might not want to login with google.

**Comment by TrySound** [comment]
Login by email and passkeys support is in progress

https://github.com/user-attachments/assets/c4146ba1-4be6-4059-be73-4498e3f42c24
