### ISSUE TITLE
Self-closing <link rel ... /> flagged as invalid HTML

### ISSUE THREAD

**Issue by paulrudy** [webstudio-is/webstudio#3698]
Minor issue:

In an HTML embed block, a self-closing `<link rel="stylesheet" src=.... />` causes a UI warning that the HTML is invalid. When clicking "Fix Automatically", it's rectified by removing the self-closing `/`.

I use Prettier for formatting my code, and it by default prefers to self-close `<link />` tags.

As far as I can tell, both versions (self-closing and not) are valid in HTML5.

Ignoring the Webstudio UI warning, the self-closing `<link .../>` still works, at least with a stylesheet. Suggestion is to allow for self-closing `<link .../>` tags without a warning.

**Comment by kof** [comment]
general recommendation is no training slash on void elements, 

<img width="1351" alt="image" src="https://github.com/webstudio-is/webstudio/assets/52824/5642209e-2330-4dc0-ab62-a9e0eaf194d6">


there must be a way to change prettier behavior, its wrong to adapt to a tool that gives you bad formatting instead of doing what standards recommend

https://validator.w3.org/nu/#textarea

**Comment by paulrudy** [comment]
Thanks, I should have done a bit more homework. 

> Here is a corresponding prettier issue [prettier/prettier#5246](https://github.com/prettier/prettier/issues/5246)

That was a pretty enlightening read. How annoying. I would have expected it to conform to standards. I'll look for an alternative.
