### ISSUE TITLE
Custom easing transition not working

### ISSUE THREAD

**Issue by johnsicili** [webstudio-is/webstudio#4197]
When selecting `custom` in easing function, it just goes to "ease".

I haven't used this before, so not sure the expectation, but maybe a field I can enter the function 🤷 

https://github.com/user-attachments/assets/e80b90e4-4632-4f5d-ac53-9035d978ed03

**Comment by JayaKrishnaNamburu** [comment]
There is no value for `custom` easing value. We usually use it as a placeholder if user adds some easing value that is not available in the rest. Reason why it's going to `ease` is, even when you select custom in the UI. There is no value that is updated there. The value is just `background-color 120ms 0ms`. So, it just shows the value as `ease` because thats the default value browsers use.

Maybe we need to improve the UX a bit here. But not a bug

**Comment by JayaKrishnaNamburu** [comment]
https://github.com/user-attachments/assets/b2717297-25b8-4664-9dd2-58b5ede5afc7
