### ISSUE TITLE
User not found 

### ISSUE THREAD

**Issue by vishnu5104** [webstudio-is/webstudio#4264]
Hi,

When I run this locally, I get a user error on GitHub even though I added the dev login as true and set auth secure to my name. When I add "vish," the first four letters, it shows "user not found. Why?

I am attaching the screenshot for your reference 
![Screenshot 2024-10-11 011915](https://github.com/user-attachments/assets/b0d65f88-c55e-4c8f-bed6-299cb75db09a)

Also why I try codebase it work but the problem when I create a new project on dashboard it shows This site can’t be reached
Check if there is a typo in p-e4441d02-2fe7-44e2-82a2-0d19f30ca576-dot-cuddly-goggles-xqr4r4rgvgjcp9jr-5173.app.github.dev.
If spelling is correct, [try running Windows Network Diagnostics](javascript:diagnoseErrors()).
DNS_PROBE_FINISHED_NXDOMAIN

link::https://p-e4441d02-2fe7-44e2-82a2-0d19f30ca576-dot-cuddly-goggles-xqr4r4rgvgjcp9jr-5173.app.github.dev/

so anyone successfully run this in locally then guide me how to do this ?

**Comment by istarkov** [comment]
Could you kindly take a moment to review [this issue](https://github.com/webstudio-is/webstudio/issues/4263) thoroughly?

Especially these points:

- Could you please explain step-by-step what you’re doing?
- I won't be able to assist further unless you provide detailed steps with screenshots.

Please take the time to carefully review and improve the clarity of your explanations. Otherwise, how can anyone provide effective help?

Thanks for your understanding.

**Comment by kevin-folo** [comment]
Same issue solved, the database migration failed during the initialization process, so you need to migrate again using "pnpm migrations migrate".
